BACKBONE:
    VOXEL_SIZE: [0.05, 0.05, 0.05]
    VOXEL_MAX: 120000
    IN_CHANNELS: 4 # coords + intensity
    CHANNELS: [32, 64, 128, 256, 256]
    BLOCK_REPS: 2
    WINDOW_SIZE: [0.3, 0.3, 0.3]
    WINDOW_SIZE_SPHERE: [2, 2, 80]
    WINDOW_SIZE_SCALE: [2.0, 1.5]
    QUANT_SIZE: [80.,80.,80.]
    QUANT_SIZE_SPHERE: [12.,12.,12.]
    DROP_PATH_RATE: 0.3
    SPHERE_LAYERS: [1,2,3,4,5]
