DECODER:
    NHEADS: 8
    DIM_FEEDFORWARD: 1024
    FEATURE_LEVELS: 3
    DEC_BLOCKS: 2
    NUM_QUERIES: 100
    HIDDEN_DIM: 256
    POS_ENC:
        MAX_FREQ: 10000
        FEAT_SIZE: 256
        DIMENSIONALITY: 3
        BASE: 2
